spring:
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.example.bkjeon.mapper
  configuration:
    cacheEnabled: false
    useGeneratedKeys: true
    defaultExecutorType: REUSE
    aggressiveLazyLoading: false
    default-statement-timeout: 30
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


# Local Env (Mysql DB)
# H2 Console
# - url: http://localhost:9090/h2-console
# - jdbc url: jdbc:h2:mem:testdb
---

spring:
  profiles: local
  datasource:
    data: classpath:sql/init_h2.sql
  h2:
    console:
      enabled: true

kafka:
  brokers: 192.168.0.203:9092,192.168.0.204:9092,192.168.0.205:9092

server:
  port: 9090

# Dev Env
---
spring:
  profiles: dev
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: root
    password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

kafka:
  brokers: 192.168.0.203:9092,192.168.0.204:9092,192.168.0.205:9092

server:
  port: 9090

# Production Env
---

spring:
  profiles: prod
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.0.207:13306/study?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
    driver-class-name: com.mysql.cj.jdbc.Driver

kafka:
  brokers: 192.168.0.203:9092,192.168.0.204:9092,192.168.0.205:9092

server:
  port: 9090
