spring:
  profiles:
    active: local

server:
  port: 9000

# Local Env
---

spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true # url: jdbc:h2:mem:testdb
  devtools:
    livereload:
      enabled: true

# Dev Env
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.207:3306/test?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

# Production Env
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.207:3306/test?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate