spring:
  profiles:
    active: local

server:
  port: 9090

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  # echo 'bkjeon-java-example-spring-boot-jpa-codebase-secret-bkjeon-java-example-spring-boot-jpa-codebase-secret' | base64
  secret: YmtqZW9uLWphdmEtZXhhbXBsZS1zcHJpbmctYm9vdC1qcGEtY29kZWJhc2Utc2VjcmV0LWJramVvbi1qYXZhLWV4YW1wbGUtc3ByaW5nLWJvb3QtanBhLWNvZGViYXNlLXNlY3JldA==
  token-validity-in-seconds: 86400

# Local Env (H2 DB)
---

spring:
  profiles: local
  datasource:
    data: classpath:sql/data-h2.sql
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace

# Dev Env (Mysql DB)
---

spring:
  profiles: local-db
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bkjeon_jpa?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driver-class-name: com.mysql.cj.jdbc.Driver
    data: classpath:sql/data-h2.sql
    initialization-mode: always
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace

# Dev Env
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    format_sql: false
    hibernate:
      ddl-auto: validate

# Production Env
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
